services:
    postgres:
        container_name: postgres_go_2
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: my_pass
            PGDATA: /data/postgres
        volumes:
            - ./postgres-data:/data/postgres
        ports:
            - "5432:5432"
